var files_list =
    [
        '../../app/collections/QuestionsCollection.js',
        '../../app/fixtures/quiz.js',
        '../../app/fixtures/score.js',
        '../../app/main.js',
        '../../app/Main.spec.js',
        '../../app/models/QuestionModel.js',
        '../../app/models/QuestionModel.spec.js',
        '../../app/models/QuizModel.js',
        '../../app/models/ScoreModel.js',
        '../../app/requirejs-config.js',
        '../../app/routers/Router.js',
        '../../app/State.js',
        '../../app/test-main.js',
        '../../app/views/HomeView.js',
        '../../app/views/QuestionsView.js',
        '../../app/views/QuestionView.js',
        '../../app/views/QuizView.js',
        '../../app/views/ScoreView.js'
    ];